<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_demo-03</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e6b7a484-f217-4451-9de5-08e6a6dbf450</testSuiteGuid>
   <testCaseLink>
      <guid>877ea070-72a7-4d0d-acb7-efcb18df8774</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMA-03</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9c678928-7b1d-48b3-9c78-0ba40ca04d80</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Raw Data/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9c678928-7b1d-48b3-9c78-0ba40ca04d80</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>468e0581-a770-48b4-b338-bb880f8f5259</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9c678928-7b1d-48b3-9c78-0ba40ca04d80</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>84c21408-5ae5-4cd1-adaf-4a6f34d3d984</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
